Apekun tasks
MikitaTsiarentsyeu/M-PT1-37-21 pull request #3
Opened 2021-03-14 11:34 UTC by zasferg

2021-03-15 10:38 UTC, MikitaTsiarentsyeu requested changes
A function is good, float-based calculation for money is not, use Decimal instead.

Also I would like you to move your file to a specific folder with your name on it.

2021-03-16 02:44 UTC, zasferg commented
Done

2021-03-18 07:50 UTC, MikitaTsiarentsyeu approved these changes
Good job, your marks are:
CW - 9.0
HW - 10.0

2021-03-18 07:50 UTC, MikitaTsiarentsyeu commented on Apekun_Dmitry_classwork_15.03.2021/lesson2.py
> +    print(a,"x^2-",b, "x+", c, "= 0")
not optimal flow control, correct though

2021-03-18 07:50 UTC, MikitaTsiarentsyeu commented on Apekun_Dmitry_homework_14.03.2021/hometask1.py
> +        depo+=per_month
a cycle is not optimal solution, there is a special formula to calculate such deposits

2021-03-18 07:50 UTC, merged