Merge pull request #1 from MikitaTsiarentsyeu/main
MikitaTsiarentsyeu/M-PT1-37-21 pull request #38
Opened 2021-03-22 20:17 UTC by RomanPutsilouski

task

2021-03-22 20:17 UTC, RomanPutsilouski commented
/

2021-03-24 08:16 UTC, MikitaTsiarentsyeu requested changes
![image](https://user-images.githubusercontent.com/57627287/112276651-08760c00-8c92-11eb-9232-82cf871a4639.png)

It's not working, and it's a mess. I strongly recommend remove all unnecessary comments (including snippet formatting like # ______________Введение времени с терминала______________) and execute both current time and user value one after another, rather then commenting one of it, it's really hard to read your code with such formatting.

2021-03-26 00:01 UTC, RomanPutsilouski commented
Добработал все+сортировку добавил

2021-03-29 00:29 UTC, RomanPutsilouski commented
finished

2021-03-29 07:44 UTC, MikitaTsiarentsyeu approved these changes
I score your homework at 8.5, classwork - at 9.0.

2021-03-29 07:44 UTC, MikitaTsiarentsyeu commented on Tasks/Putsilouski_Tasks/CW/1/claswork.py
> +for i in range(len(c)):
and technically it's a new variable, you're supposed to use c in every loop (God knows how)

2021-03-29 07:44 UTC, MikitaTsiarentsyeu commented on Tasks/Putsilouski_Tasks/Task2/HW2new.py
> +    sys.exit("Неверный формат, начни заново")
good validation

2021-03-29 07:46 UTC, merged