Titov task2
MikitaTsiarentsyeu/M-PT1-37-21 pull request #42
Opened 2021-03-23 19:12 UTC by titov-evgeni

2021-03-24 07:51 UTC, MikitaTsiarentsyeu requested changes
![image](https://user-images.githubusercontent.com/57627287/112273501-7a4c5680-8c8e-11eb-946b-22a2beb61c59.png)

a minor issue but still, it's here

2021-03-24 14:25 UTC, titov-evgeni commented
i made changes

2021-03-25 10:50 UTC, MikitaTsiarentsyeu approved these changes
Good job, the logic is totally correct, I have no nitpicks. Your score is 9.0.

2021-03-25 10:50 UTC, MikitaTsiarentsyeu commented on Tasks/Task2/task_2.py
> +        0: "Полночь",
nice touch

2021-03-25 10:50 UTC, merged