Ramanenka_tasks
MikitaTsiarentsyeu/M-PT1-37-21 pull request #43
Opened 2021-03-24 03:52 UTC by margoroma

2021-03-24 07:46 UTC, MikitaTsiarentsyeu requested changes

2021-03-24 07:46 UTC, MikitaTsiarentsyeu commented on Tasks/RM_HomeTask2+.py
> +                            mins = d_m.get(key)
![image](https://user-images.githubusercontent.com/57627287/112273136-1033b180-8c8e-11eb-9acf-e533ed4da5e7.png)

There will be an error for the value 12:00

2021-03-24 09:38 UTC, MikitaTsiarentsyeu commented
And now test it for value 24:00

2021-03-24 11:07 UTC, margoroma commented
А зараз бачна?)

2021-03-25 06:37 UTC, margoroma commented
Last-Version

2021-03-25 10:45 UTC, MikitaTsiarentsyeu approved these changes
Great job, I would use the same logic. Explicitly showing time format and validation rules are also a good decisions. Your score is 9.5.

2021-03-25 10:46 UTC, merged