Changes
MikitaTsiarentsyeu/M-PT1-37-21 pull request #50
Opened 2021-03-26 15:29 UTC by margoroma

move folders

2021-03-28 14:22 UTC, margoroma commented
Самостоятельная, задание 4.

2021-03-28 18:41 UTC, margoroma commented
added Test_classwork

2021-03-29 07:50 UTC, MikitaTsiarentsyeu requested changes

2021-03-29 07:50 UTC, MikitaTsiarentsyeu commented on Ramanenka_Tasks/Test1/RM_ClassWork_zadanie4.py
> +chisla = [5, 13, 2, 11, 17, 2, 1, 13, 10, 4, 8, 5, 19]
and what if those numbers in the string were presented in a different order?

2021-03-29 07:50 UTC, MikitaTsiarentsyeu commented on Ramanenka_Tasks/Test1/RM_ClassWork_zadanie4.py
> +        new_list_uniq.append(i)
totally not optimal solution

2021-03-29 07:50 UTC, MikitaTsiarentsyeu commented on Ramanenka_Tasks/Test1/RM_ClassWork_zadanie4.py
> +    new_list_uniq[mini], new_list_uniq[i] = new_list_uniq[i], new_list_uniq[mini]
you could use standard python sorting here actually

2021-03-29 07:50 UTC, MikitaTsiarentsyeu commented on Ramanenka_Tasks/Test1/RM_ClassWork_zadanie4.py
> +for i in range(3):                              # Мат. операции
wtf is range(3)? rework it to be range of your list in general case

2021-04-02 09:28 UTC, closed without merging