выполнил тест,вроде
MikitaTsiarentsyeu/M-PT1-37-21 pull request #59
Opened 2021-03-26 21:42 UTC by Edward9601

не судите строго)

2021-03-29 08:33 UTC, MikitaTsiarentsyeu requested changes
The idea with zip is good, but realization is not exactly correct, please rework it.

2021-03-29 08:33 UTC, MikitaTsiarentsyeu commented on Dumbuya_Test1/main.py
> +          'five': 5, 'nineteen': 19}
OK, so you have this dictionary, but where is the original string you supposed to work with?

2021-03-29 08:33 UTC, MikitaTsiarentsyeu commented on Dumbuya_Test1/main.py
> +list_mult = [((x * y), (x + y)) for (x, y) in zip(no_dublicates2[:-1], no_dublicates2[1:])]
not exactly correct, the operations must alternate for different elements, mult for first pair, sum for second and so on

2021-03-29 12:44 UTC, Edward9601 commented
About the last thing, did you mean that it should multiply 1st and 2d index, then sum 2d and 3rd and so on?

Sent from my iPhone

> On Mar 29, 2021, at 11:33 AM, MikitaTsiarentsyeu ***@***.***> wrote:
> 
> ﻿
> @MikitaTsiarentsyeu requested changes on this pull request.
> 
> The idea with zip is good, but realization is not exactly correct, please rework it.
> 
> In Dumbuya_Test1/main.py:
> 
> > +string = {'five': 5, 'thirteen': 13, 'two': 2, 'eleven': 11, 'seventeen': 17,
> +          'two': 2, 'one': 1, 'thirteen': 13, 'ten': 10, 'four': 4, 'eight': 8,
> +          'five': 5, 'nineteen': 19}
> OK, so you have this dictionary, but where is the original string you supposed to work with?
> 
> In Dumbuya_Test1/main.py:
> 
> > +
> +if len(a) == len(b):
> +    for i in range(len(a)):
> +        if a[i] == b[i]:
> +            print('Equal')
> +        else:
> +            print('Not equal')
> +
> +string = {'five': 5, 'thirteen': 13, 'two': 2, 'eleven': 11, 'seventeen': 17,
> +          'two': 2, 'one': 1, 'thirteen': 13, 'ten': 10, 'four': 4, 'eight': 8,
> +          'five': 5, 'nineteen': 19}
> +
> +values = string.values()
> +no_dublicates = set(values)
> +no_dublicates2 = list(no_dublicates)
> +list_mult = [((x * y), (x + y)) for (x, y) in zip(no_dublicates2[:-1], no_dublicates2[1:])]
> not exactly correct, the operations must alternate for different elements, mult for first pair, sum for second and so on
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-02 09:31 UTC, MikitaTsiarentsyeu approved these changes
Good job, your score is 9.0

2021-04-02 09:31 UTC, MikitaTsiarentsyeu commented on Dumbuya_Test1/main.py
> +last_action = True
nitpick: not very good name for a variable, someone could think that it's not a switch for every action, but a cycle breaker.

2021-04-02 09:32 UTC, merged